# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Snapcode SVG
email: joshre@me.com
description: > # this means to ignore newlines until "baseurl:"
  Type in your snapchat username and get your snapcode as an SVG.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://joshre.com/snapcode-svg/" # the base hostname & protocol for your site
twitter_username: jawshre
github_username:  joshre

# Build settings
markdown: kramdown

sass:
  style: :compressed